version: 2

jobs:
  deploy:
    docker:
      - image: cypress/base:8

    steps:
      - checkout
      - run:
          name: Pull submodules
          command: |
            git submodule init
            git submodule update --recursive --remote

      - run:
          name: Deploying
          command: sh deploy.sh

workflows:
  version: 2
  commit:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *" # Every day
          filters:
            branches:
              only:
                - master
    jobs:
      - deploy
