version: 2

jobs:
  deploy:
    docker:
      - image: cypress/base:8

    steps:
      - checkout
      - run:
          name: Pull submodules
          command: |
            git submodule init
            git submodule update --recursive --remote

      - run:
          name: Deploying
          command: sh deploy.sh

workflows:
   version: 2
   nightly:
     triggers:
       - schedule:
           cron: "0 0 */3 * *" # 3 days
           filters:
             branches:
               only:
                 - master
     jobs:
       - deploy
